### ISSUE TITLE
搭建一个Ubuntu的桌面系统（带VNC/noVNC）

### ISSUE THREAD

**Issue by Zakariyya** [Zakariyya/blog#158]
> GitHub项目地址：https://github.com/fcwu/docker-ubuntu-vnc-desktop
Docker Hub：https://hub.docker.com/r/imlala/ubuntu-xfce-vnc-novnc

```
apt update -y  # 升级packages

apt install wget  #如果出现 wget:command not found,可以用这个命令安装
```
## 创建安装目录
```
mkdir -p /root/data/docker_data/Ubuntu_desktop
cd /root/data/docker_data/Ubuntu_desktop
vim docker-compose.yml
```

## docker-compose.yml 填入以下内容：
```
version: '3.5'

services:
    ubuntu-xfce-vnc:
        container_name: xfce
        image: imlala/ubuntu-xfce-vnc-novnc:latest
        shm_size: "1gb"  # 防止高分辨率下Chromium崩溃,如果内存足够也可以加大一点点
        ports:
            - 5900:5900   # TigerVNC的服务端口（保证端口是没被占用的，冒号右边的端口不能改，左边的可以改）
            - 6080:6080   # noVNC的服务端口，注意事项同上
        environment: 
            - VNC_PASSWD=PAS3WorD    # 改成你自己想要的密码
            - GEOMETRY=1280x720      # 屏幕分辨率，800×600/1024×768诸如此类的可自己调整
            - DEPTH=24               # 颜色位数16/24/32可用，越高画面越细腻，但网络不好的也会更卡
        volumes: 
            - ./Downloads:/root/Downloads  # Chromium/Deluge/qBittorrent/Transmission下载的文件默认保存位置都是root/Downloads下
            - ./Documents:/root/Documents  # 映射一些其他目录
            - ./Pictures:/root/Pictures
            - ./Videos:/root/Videos
            - ./Music:/root/Music
        restart: unless-stopped
```

## 执行
```
docker-compose up -d 
```

***
### 参考资料
- https://blog.laoda.de/archives/install-ubuntu-desktop
- https://lala.im/6714.html
- https://github.com/fcwu/docker-ubuntu-vnc-desktop
- http://blog.51sec.org/2021/01/install-ubuntu-1804-xfce4-desktop-in.html
